### ISSUE TITLE
Routing policy (geolocation)

### ISSUE THREAD

**Issue by kablamo** [odyniec/p5-WebService-Amazon-Route53#2]
Hi, I'm considering adding the ability to specify a routing policy in `change_resource_record_sets()`.  I'm especially interested in the geolocation routing policy (http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Requests.html#API_ChangeResourceRecordSets_RequestGeoSyntax).

Would you be interested in a pull request that added that feature?

**Comment by odyniec** [comment]
Sure. Actually someone asked me about this a few days ago, but I didn't have the time to look into it yet.

**Comment by kablamo** [comment]
Cool!  Actually that was a coworker who emailed you.  I will be in touch with a pull request soon.

**Comment by kablamo** [comment]
We got overexcited.  It turns out we really wanted latency based routing which is a feature you already have.  Thanks for a great module btw.

**Comment by odyniec** [comment]
No worries. Glad to know it's useful.
